{"cause":{"broker":"localhost:9092","code":"ECONNREFUSED","name":"KafkaJSConnectionError","retriable":true},"level":"error","message":"Failed to connect Kafka producer: Connection error: ","name":"KafkaJSNumberOfRetriesExceeded","retriable":false,"retryCount":8,"retryTime":30000,"service":"manufacturing-backend","stack":"KafkaJSNonRetriableError\n  Caused by: KafkaJSConnectionError: Connection error: \n    at Socket.onError (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\network\\connection.js:210:23)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-20 18:58:14"}
{"cause":{"broker":"localhost:9092","code":"ECONNREFUSED","name":"KafkaJSConnectionError","retriable":true},"level":"error","message":"Failed to connect Kafka producer: Connection error: ","name":"KafkaJSNumberOfRetriesExceeded","retriable":false,"retryCount":8,"retryTime":16462,"service":"manufacturing-backend","stack":"KafkaJSNonRetriableError\n  Caused by: KafkaJSConnectionError: Connection error: \n    at Socket.onError (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\network\\connection.js:210:23)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-20 19:00:26"}
{"cause":{"broker":"localhost:9092","code":"ECONNREFUSED","name":"KafkaJSConnectionError","retriable":true},"level":"error","message":"Failed to connect Kafka producer: Connection error: ","name":"KafkaJSNumberOfRetriesExceeded","retriable":false,"retryCount":8,"retryTime":30000,"service":"manufacturing-backend","stack":"KafkaJSNonRetriableError\n  Caused by: KafkaJSConnectionError: Connection error: \n    at Socket.onError (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\network\\connection.js:210:23)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-20 19:02:56"}
{"cause":{"broker":"localhost:9092","code":"ECONNREFUSED","name":"KafkaJSConnectionError","retriable":true},"level":"error","message":"Failed to connect Kafka producer: Connection error: ","name":"KafkaJSNumberOfRetriesExceeded","retriable":false,"retryCount":8,"retryTime":30000,"service":"manufacturing-backend","stack":"KafkaJSNonRetriableError\n  Caused by: KafkaJSConnectionError: Connection error: \n    at Socket.onError (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\network\\connection.js:210:23)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-20 19:03:41"}
{"cause":{"broker":"localhost:9092","code":"ECONNREFUSED","name":"KafkaJSConnectionError","retriable":true},"level":"error","message":"Failed to connect Kafka producer: Connection error: ","name":"KafkaJSNumberOfRetriesExceeded","retriable":false,"retryCount":8,"retryTime":21226,"service":"manufacturing-backend","stack":"KafkaJSNonRetriableError\n  Caused by: KafkaJSConnectionError: Connection error: \n    at Socket.onError (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\network\\connection.js:210:23)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-20 19:06:18"}
{"code":3,"level":"error","message":"Failed to create consumer for group manufacturing-orders-group: This server does not host this topic-partition","name":"KafkaJSProtocolError","retriable":true,"service":"manufacturing-backend","stack":"KafkaJSProtocolError: This server does not host this topic-partition\n    at createErrorFromCode (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\protocol\\error.js:581:10)\n    at Object.parse (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\protocol\\requests\\metadata\\v0\\response.js:55:11)\n    at Connection.send (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\network\\connection.js:433:35)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async [private:Broker:sendRequest] (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\broker\\index.js:904:14)\n    at async Broker.metadata (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\broker\\index.js:177:12)\n    at async D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\cluster\\brokerPool.js:158:25\n    at async D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\cluster\\index.js:111:14\n    at async Cluster.refreshMetadata (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\cluster\\index.js:172:5)\n    at async Cluster.addMultipleTargetTopics (D:\\hackathon\\codewarrior\\backend\\node_modules\\kafkajs\\src\\cluster\\index.js:230:11)","timestamp":"2025-09-20 19:13:08","type":"UNKNOWN_TOPIC_OR_PARTITION"}
{"error":"Validation error: Email or username is required","ip":"::1","level":"error","message":"Error occurred:","method":"POST","service":"manufacturing-backend","stack":"Error: Validation error: Email or username is required\n    at <anonymous> (D:\\hackathon\\codewarrior\\backend\\src\\middleware\\validation.middleware.ts:18:13)\n    at Layer.handle [as handle_request] (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:47:12)","timestamp":"2025-09-20 19:22:02","url":"/api/auth/login","userAgent":"Mozilla/5.0 (Windows NT; Windows NT 10.0; en-IN) WindowsPowerShell/5.1.26100.6584"}
{"code":"28P01","file":"auth.c","length":100,"level":"error","line":"332","message":"Signup error: password authentication failed for user \"user\"","name":"error","routine":"auth_failed","service":"manufacturing-backend","severity":"FATAL","stack":"error: password authentication failed for user \"user\"\n    at D:\\hackathon\\codewarrior\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async AuthService.signup (D:\\hackathon\\codewarrior\\backend\\src\\modules\\auth\\auth.service.ts:13:31)\n    at async signup (D:\\hackathon\\codewarrior\\backend\\src\\modules\\auth\\auth.controller.ts:23:22)","timestamp":"2025-09-20 19:31:25"}
{"code":"28P01","file":"auth.c","length":100,"level":"error","line":"332","message":"Signup controller error: password authentication failed for user \"user\"","name":"error","routine":"auth_failed","service":"manufacturing-backend","severity":"FATAL","stack":"error: password authentication failed for user \"user\"\n    at D:\\hackathon\\codewarrior\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async AuthService.signup (D:\\hackathon\\codewarrior\\backend\\src\\modules\\auth\\auth.service.ts:13:31)\n    at async signup (D:\\hackathon\\codewarrior\\backend\\src\\modules\\auth\\auth.controller.ts:23:22)","timestamp":"2025-09-20 19:31:25"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::3000","port":3000,"service":"manufacturing-backend","stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1907:16)\n    at listenInCluster (node:net:1964:12)\n    at Server.listen (node:net:2066:7)\n    at Function.listen (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\hackathon\\codewarrior\\backend\\src\\index.ts:33:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-09-20 19:38:30"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::3001","port":3001,"service":"manufacturing-backend","stack":"Error: listen EADDRINUSE: address already in use :::3001\n    at Server.setupListenHandle [as _listen2] (node:net:1907:16)\n    at listenInCluster (node:net:1964:12)\n    at Server.listen (node:net:2066:7)\n    at Function.listen (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (D:\\hackathon\\codewarrior\\backend\\src\\index.ts:33:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-09-20 19:40:16"}
{"error":"Validation error: Username is required","ip":"::1","level":"error","message":"Error occurred:","method":"POST","service":"manufacturing-backend","stack":"Error: Validation error: Username is required\n    at D:\\hackathon\\codewarrior\\backend\\dist\\middleware\\validation.middleware.js:16:19\n    at Layer.handle [as handle_request] (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (D:\\hackathon\\codewarrior\\backend\\node_modules\\express\\lib\\router\\index.js:47:12)","timestamp":"2025-09-20 20:17:48","url":"/api/auth/signup","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0"}
